Updated Functions v2.0.1
BoxOfDevs/Functions pull request #17
Opened 2018-07-29 08:36 UTC by JackMD

## Description
* Updated api for latest pockeetmine-mp release.
* Fixed command not being removed.

2018-07-29 09:25 UTC, HimbeersaftLP requested changes
~~Seems to be working for me, but I see no reason to remove all those previous API versions.~~
See [new comment](https://github.com/BoxOfDevs/Functions/pull/17#issuecomment-408664390)

2018-07-29 09:25 UTC, HimbeersaftLP commented on plugin.yml
> -api: [3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14]
~~Why remove all those? You didn't change anything that breaks bc.~~
See [new comment](https://github.com/BoxOfDevs/Functions/pull/17#issuecomment-408664390)

2018-07-29 09:27 UTC, Ifera reviewed
Since the commands were not being removed before hand due to a typo, [this](https://github.com/BoxOfDevs/Functions/pull/17/commits/a7c706b4f2f5c6d03661e17dcd4ad4477180a235) to be exact

2018-07-29 09:30 UTC, HimbeersaftLP commented
I'm not talkinga about the plugin version, I mean the API version.

2018-07-29 09:33 UTC, HimbeersaftLP commented on plugin.yml
> +api: [3.0.0-ALPHA12, 3.0.0]
I swear there were more of them before, considering we advertise that compatibility in the README and that it's supported, I see no reason not to add them

2018-07-29 09:38 UTC, HimbeersaftLP approved these changes

2018-07-29 09:39 UTC, HimbeersaftLP commented
Sorry for my stupidness, I didn't read the numbers and thought those were older ones, I wonder who added them though, as that was a really bad idea.

2018-07-31 14:26 UTC, Ad5001 approved these changes
Seems good to me.

2018-07-31 14:48 UTC, lavender-sys approved these changes

2018-07-31 17:30 UTC, merged